Stop synchronizing with the guest RTC
Synchronizing with the guest RTC leads to the following error on
fc32:

```
error: internal error: unable to execute QEMU agent command
'guest-set-time': hwclock failed to set hardware clock to system time
```

Since we are setting the date/time from the host's datetime.now,
there is no need to ask libvirt to sync it.

The same issue can be observed by calling the following command
on a virt-launcher pod:

```
virsh domtime 1 --sync
```

Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>